name: Upload Python Package

on: push

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
#    - uses: actions/checkout@v2
#    - name: Set up Python
#      uses: actions/setup-python@v2
#      with:
#        python-version: '3.x'
#    - name: Install dependencies
#      run: |
#        python -m pip install --upgrade pip
#        pip install setuptools wheel twine
#    - name: Build and publish
#      env:
#        TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
#        TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
#      run: |
#        python setup.py sdist bdist_wheel
#        twine upload dist/*
    # checkout multiple repos
    - name: List crap
      run: |
        pwd
#        command -V python
#        command -V pip
    - name: Checkout
      uses: actions/checkout@v2
      with:
        path: main

    - name: Checkout bolt-python repo
      uses: actions/checkout@v2
      with:
        fetch-depth: 0  # all tags everything
        ref: main  # specific branch
        repository: slackapi/bolt-python
        path: bolt-python

    - name: List crap
      run: |
        pwd
        ls -laF
        ls -laF bolt-python
        ls -laF main

  # https://github.com/marketplace/actions/deploy-to-github-pages
#  build-and-deploy:
#    runs-on: ubuntu-latest
#    steps:
#      - name: Checkout 🛎️
#        uses: actions/checkout@v2.3.1 # If you're using actions/checkout@v2 you must set persist-credentials to false in most cases for the deployment to work correctly.
#        with:
#          persist-credentials: false
#
#      - name: Install and Build 🔧 # This example project is built using npm and outputs the result to the 'build' folder. Replace with the commands required to build your project, or remove this step entirely if your site is pre-built.
#        run: |
#          npm install
#          npm run build
#
#      - name: Deploy 🚀
#        uses: JamesIves/github-pages-deploy-action@3.6.1
#        with:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#          BRANCH: gh-pages # The branch the action should deploy to.
#          FOLDER: build # The folder the action should deploy.
#          CLEAN: true # Automatically remove deleted files from the deploy branch